# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)
%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126


### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(7,7)
rand_tensor


tensor([[0.5500, 0.2900, 0.3353, 0.0190, 0.2859, 0.7914, 0.2482],
        [0.8120, 0.8150, 0.8871, 0.0799, 0.4532, 0.6040, 0.2436],
        [0.6612, 0.7094, 0.1254, 0.1595, 0.9230, 0.4435, 0.4124],
        [0.8226, 0.3798, 0.0786, 0.7905, 0.3692, 0.9008, 0.9307],
        [0.9278, 0.1189, 0.9065, 0.0210, 0.2942, 0.8377, 0.8364],
        [0.9932, 0.1177, 0.7243, 0.3671, 0.4095, 0.4626, 0.8948],
        [0.3603, 0.7223, 0.0779, 0.1383, 0.7488, 0.1210, 0.8492]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
rand_tensor2 = torch.rand(1,7)
# Perform matrix multiplication
mult_result = torch.matmul(rand_tensor, rand_tensor2.T)
mult_result


tensor([[1.1549],
        [2.1935],
        [1.4961],
        [1.4492],
        [2.1746],
        [2.1206],
        [1.2212]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
seed = 0

# Create two random tensors
torch.manual_seed(seed)
rand_tensor1 = torch.rand(7, 7)
rand_tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
mult_result = torch.matmul(rand_tensor1, rand_tensor2.T)
mult_result, mult_result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.is_available()
seed = 1234
torch.cuda.manual_seed(seed)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
seed = 1234
# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')
# Create two random tensors on GPU
torch.manual_seed(seed)
tensor1 = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)
tensor1, tensor2


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
tenMul = torch.matmul(tensor1, tensor2.T)
tenMul, tenMul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [26]:
# Find max
print(tenMul.max())
# Find min
print(tenMul.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
# Find arg max
print(tenMul.argmax())
# Find arg min
print(tenMul.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [34]:
# Set seed
seed = 7

# Create random tensor
torch.manual_seed(seed)
tensor1 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
